const CALLBACK_HANDLER = {
  CHANGE_TITLE: "CHANGE_TITLE",
  CHANGE_CONTENT: "CHANGE_CONTENT",
  CHANGE_TAGS: "CHANGE_TAGS",
  ADD_THUMBNAIL: "ADD_THUMBNAIL",
  CREATE_MEMORY: "CREATE_MEMORY",
  RESET_INPUT: "RESET_INPUT",
  CHANGE_AUTHOR: "CHANGE_AUTHOR",
};

export default CALLBACK_HANDLER;
