const CALLBACK_HANDLER_CONSTANTS = {
  EDIT_MEMORY: "EDIT_MEMORY",
  DELETE_MEMORY: "DELETE_MEMORY",
  CLICKED_POPUP_MENU: "CLICKED_POPUP_MENU",
  LIKE_MEMORY: "LIKE_MEMORY",
};

export default CALLBACK_HANDLER_CONSTANTS;
